name: Scheduled Python Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

permissions:
  contents: write  # Grants write permissions to the workflow

jobs:
  run-python-script:
    runs-on: todoespi

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install Python package
      run: |
        pip install pysondb beautifulsoup4 requests 

    - name: Run Python script
      run: python estrims.py
      env:
        API_KEY: ${{ secrets.API_KEY }}

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and push changes
      run: |
        git add data.json
        git commit -m "Auto-commit generated file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
